collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2756546512246132
color:
  saturation: 0.8295996678061783
  brandStrength: 0.09607764217071235
  lightness: 0.3227976425550878
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  rhythmicContrast: 0.5936769982799888
layout_spectrum: 0.7002857071347535
name: Round One
