collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.8138256245292723
color:
  saturation: 0.8865236372221261
  brandStrength: 0.25278831529431045
  lightness: 0.7950112912803888
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  rhythmicContrast: 0.18126177927479148
layout_spectrum: 0.7917206799611449
name: Round One
