collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2756546512246132
color:
  saturation: 0.9528153177816421
  brandStrength: 0.08007806236855686
  lightness: 0.6093204887583852
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  rhythmicContrast: 0.2339331607799977
layout_spectrum: 0.40028807427734137
name: Round One
